<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Page creation error!' => 'Ошибка создания страницы!',
    'Active' => 'Активная',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить эту запись?',
    'Create' => 'Создать',
    'Create {modelClass}' => 'Создание {modelClass}',
    'Create page' => 'Создать страницу',
    'Created' => 'Создано',
    'Created At' => 'Дата создания',
    'Delete' => 'Удалить',
    'ID' => '',
    'Key' => 'Ключ',
    'Title' => 'Заголовок',
    'Description' => 'Описание',
    'Position' => 'Позиция',
    'Modified' => 'Отредактировано',
    'Search' => 'Поиск',
    'Setting' => 'Настройка',
    'Settings' => 'Настройки',
    'Create Setting group' => 'Добавить группу',
    'Setting Group ID' => 'ID группы настроек',
    'Save' => 'Сохранить',
    'Type' => 'Тип',
    'Pages' => 'Страницы',
    'Content' => 'Текст страницы',
    'Update' => 'Редактировать',
    'Update page' => 'Обновить страницу',
    'Update {modelClass}: ' => 'Редактирование {modelClass}: ',
    'Value' => 'Значение',
    'Please select correct type' => 'Выберите допустимый тип',
    'string' => 'Строка',
    'integer' => 'Целое число',
    'boolean' => '0 или 1',
    'float' => 'Число',
    'email' => 'E-mail',
    'ip' => 'IP',
    'url' => 'URL',
    'object' => 'JSON',
    'Edit' => 'Редактировать',
    // SEO поля
    'SEO Settings' => 'SEO Настройки',
    'Title for search engines (50-60 characters)' => 'Заголовок для поисковиков (50-60 символов)',
    'Page description for search engines (150-160 characters)' => 'Описание для поисковиков (150-160 символов)',
    'Comma-separated keywords' => 'Ключевые слова через запятую',
    'Social Media (OpenGraph)' => 'Социальные сети (OpenGraph)',
    'Title for social networks' => 'Заголовок для соцсетей',
    'Description for social networks' => 'Описание для соцсетей',
    'URL of image for social networks (1200x630 recommended)' => 'URL изображения для соцсетей (рекомендуется 1200x630)',
    
    'Meta Title' => 'Мета-заголовок (SEO)',
    'Meta Description' => 'Мета-описание (SEO)',
    'Meta Keywords' => 'Ключевые слова (SEO)',
    'OG Title' => 'Заголовок для соцсетей (OpenGraph)',
    'OG Description' => 'Описание для соцсетей (OpenGraph)',
    'OG Image' => 'Изображение для соцсетей (OpenGraph)',
];
